# Generated by Django 3.0.6 on 2020-05-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='sell_price',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=8),
            preserve_default=False,
        ),
    ]
