# Generated by Django 3.0.6 on 2020-05-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200514_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier_price',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
