# Generated by Django 3.0.6 on 2020-05-07 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200507_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Office'),
            preserve_default=False,
        ),
    ]
