# Generated by Django 3.0.6 on 2020-05-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200517_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier_price',
            field=models.FloatField(),
        ),
    ]
