# Generated by Django 3.0.6 on 2020-05-19 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200517_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ac_name', models.CharField(max_length=100)),
                ('ac_number', models.DecimalField(decimal_places=0, max_digits=20)),
                ('branch', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('account_type', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], max_length=1)),
                ('description', models.TextField()),
                ('transaction_type', models.CharField(choices=[('W', 'Withdraw'), ('D', 'Deposite')], max_length=1)),
                ('amount', models.FloatField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bank')),
            ],
        ),
    ]
