# Generated by Django 3.0.6 on 2020-05-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_office'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='office',
        ),
    ]
