# Generated by Django 3.0.6 on 2020-05-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bank_banktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='date',
            field=models.DateField(),
        ),
    ]
