# Generated by Django 3.0.6 on 2020-05-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200519_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
