# Generated by Django 3.0.6 on 2020-09-27 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200927_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Office'),
        ),
    ]
