# Generated by Django 3.0.6 on 2020-09-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200927_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.FloatField(default=0.0),
        ),
    ]
