# Generated by Django 3.0.6 on 2020-11-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201104_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=12312, max_length=14),
            preserve_default=False,
        ),
    ]
