# Generated by Django 3.0.7 on 2020-11-06 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('core', '0018_auto_20201105_0625'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Office',
            new_name='Organization',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='office',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='office',
            new_name='organization',
        ),
        migrations.RemoveField(
            model_name='department',
            name='office',
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
            preserve_default=False,
        ),
    ]
