# Generated by Django 3.0.7 on 2020-11-18 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0012_remove_sellproduct_chalan'),
        ('core', '0020_auto_20201109_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='chalan',
        ),
        migrations.DeleteModel(
            name='Chalan',
        ),
    ]
