# Generated by Django 3.0.7 on 2020-11-18 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201118_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='organization',
        ),
    ]
