# Generated by Django 3.0.7 on 2020-11-18 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
