# Generated by Django 3.0.7 on 2020-11-18 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, to='core.Subcategory'),
            preserve_default=False,
        ),
    ]
