# Generated by Django 3.0.6 on 2020-09-27 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200927_1726'),
        ('purchase', '0002_auto_20200927_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseproduct',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
            preserve_default=False,
        ),
    ]
