# Generated by Django 3.0.6 on 2020-10-03 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201002_1710'),
        ('purchase', '0003_purchaseproduct_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseproduct',
            name='chalan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Chalan'),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Category'),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.Supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Warehouse'),
        ),
    ]
