# Generated by Django 3.0.7 on 2020-11-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_auto_20201003_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='chalan',
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
