# Generated by Django 3.0.7 on 2020-11-09 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_auto_20201109_0935'),
        ('purchase', '0005_auto_20201109_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseproduct',
            old_name='price',
            new_name='cost_price',
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='name',
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Bank'),
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='check_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='check_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='payment_type',
            field=models.CharField(choices=[('bank', 'Bank'), ('cash', 'Cash')], default='cash', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='product_name',
            field=models.CharField(default='asdf', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='remark',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
