# Generated by Django 3.0.7 on 2020-11-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_auto_20201109_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
