# Generated by Django 3.0.6 on 2020-10-02 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0013_auto_20201002_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chalan_In',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chalan_name', models.CharField(max_length=254)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('product', models.ManyToManyField(to='core.Product')),
            ],
            options={
                'verbose_name_plural': 'Chalan In',
            },
        ),
        migrations.CreateModel(
            name='Chalan_Out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chalan_name', models.CharField(max_length=254)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('chalan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chalan.Chalan_In')),
                ('product', models.ManyToManyField(to='core.Product')),
            ],
            options={
                'verbose_name_plural': 'Chalan Out',
            },
        ),
    ]
