# Generated by Django 3.0.6 on 2020-10-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chalan_in',
            name='description',
            field=models.TextField(default='asdfasd', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chalan_out',
            name='description',
            field=models.TextField(default='dsdf', max_length=254),
            preserve_default=False,
        ),
    ]
