# Generated by Django 3.0.6 on 2020-06-10 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellproduct',
            name='Product',
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Product'),
        ),
    ]
