# Generated by Django 3.0.6 on 2020-06-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_auto_20200610_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=500),
            preserve_default=False,
        ),
    ]
