# Generated by Django 3.0.6 on 2020-06-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_auto_20200610_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellproduct',
            name='added_by',
        ),
    ]
