# Generated by Django 3.0.6 on 2020-06-15 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_remove_sellproduct_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproduct',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sell.Customer'),
        ),
    ]
