# Generated by Django 3.0.6 on 2020-06-15 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0005_auto_20200615_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproduct',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.Customer'),
        ),
    ]
