# Generated by Django 3.0.6 on 2020-11-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0009_auto_20201003_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
