# Generated by Django 3.0.6 on 2020-11-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0010_auto_20201105_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
