# Generated by Django 3.0.7 on 2020-11-18 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0011_auto_20201105_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellproduct',
            name='chalan',
        ),
    ]
